### ISSUE TITLE
Git submodules

### ISSUE THREAD

**Issue by poulson** [mandli/storm_surge#1]
Hi Kyle,

I have been in a similar situation, where one of my repositories contains another repository, but I didn't want to manually maintain the subproject. It turns out (h/t to Jed Brown) that git submodules solve this exact issue. You may want to look at how I handled maintaining Elemental as a subproject of Clique:
    https://github.com/poulson/Clique

Jack

**Comment by mandli** [comment]
We use submodules now in Clawpack to manage all the different packages.  We have a love/hate relationship with them but I have found them to be extremely useful.

Have you ever tried out git subtree?

**Comment by poulson** [comment]
I'm glad to hear that you're already aware of it, I've only recently learned of git submodules (I only recently fully migrated over from mercurial). I haven't tried out git subtree, as submodules seem to be satisfying my current demands. My only criticism is that initializing them requires different commands depending upon how old your installation of git is (and my clusters tend to have old versions). Carry on!
